In [1]:
import pandas as pd

In [2]:
url ='https://raw.githubusercontent.com/bellatqu/FTI_Project_WorldHealth/refs/heads/main/chronic_disease_data.csv'
df = pd.read_csv(url)
df.head()

,year,state_code,state_name,health_topic,indicator_metric,measurement_type,numeric_value,demographic_group
0,2019,AL,Alabama,Tobacco,Quit attempts in the past year among adult cur...,Crude Prevalence,NaN,"Hawaiian or Pacific Islander, non-Hispanic"
1,2019,CT,Connecticut,Cardiovascular Disease,High cholesterol among adults who have been sc...,Crude Prevalence,30.0,Hispanic
2,2019,DE,Delaware,Cardiovascular Disease,High blood pressure among adults,Crude Prevalence,38.8,"White, non-Hispanic"
3,2019,DE,Delaware,Cardiovascular Disease,Diseases of the heart mortality among all peop...,Number,2053.0,Overall
4,2019,DE,Delaware,Diabetes,Gestational diabetes among women with a recent...,Crude Prevalence,12.5,"White, non-Hispanic"

In [3]:
df.info

<bound method DataFrame.info of        year state_code      state_name            health_topic  \
0      2019         AL         Alabama                 Tobacco
1      2019         CT     Connecticut  Cardiovascular Disease
2      2019         DE        Delaware  Cardiovascular Disease
3      2019         DE        Delaware  Cardiovascular Disease
4      2019         DE        Delaware                Diabetes
...     ...        ...             ...                     ...
43980  2022         VT         Vermont                 Tobacco
43981  2022         UT            Utah                 Tobacco
43982  2022         WY         Wyoming                 Tobacco
43983  2022         VA        Virginia                 Tobacco
43984  2022         VI  Virgin Islands                 Tobacco

                                        indicator_metric  \
0      Quit attempts in the past year among adult cur...
1      High cholesterol among adults who have been sc...
2                       High blood pressure among adults
3      Diseases of the heart mortality among all peop...
4      Gestational diabetes among women with a recent...
...                                                  ...
43980  Quit attempts in the past year among adult cur...
43981             Current cigarette smoking among adults
43982             Current cigarette smoking among adults
43983             Current cigarette smoking among adults
43984  Quit attempts in the past year among adult cur...

              measurement_type  numeric_value  \
0             Crude Prevalence            NaN
1             Crude Prevalence           30.0
2             Crude Prevalence           38.8
3                       Number         2053.0
4             Crude Prevalence           12.5
...                        ...            ...
43980  Age-adjusted Prevalence            NaN
43981         Crude Prevalence            7.1
43982         Crude Prevalence            NaN
43983  Age-adjusted Prevalence           12.3
43984  Age-adjusted Prevalence            NaN

                                    demographic_group
0          Hawaiian or Pacific Islander, non-Hispanic
1                                            Hispanic
2                                 White, non-Hispanic
3                                             Overall
4                                 White, non-Hispanic
...                                               ...
43980                       Multiracial, non-Hispanic
43981                                        Hispanic
43982                       Multiracial, non-Hispanic
43983                                         Overall
43984  American Indian or Alaska Native, non-Hispanic

[43985 rows x 8 columns]>

In [4]:
df.columns

Index(['year', 'state_code', 'state_name', 'health_topic', 'indicator_metric',
       'measurement_type', 'numeric_value', 'demographic_group'],
      dtype='object')

In [5]:
df.shape

(43985, 8)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43985 entries, 0 to 43984
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   year               43985 non-null  int64
 1   state_code         43985 non-null  object
 2   state_name         43985 non-null  object
 3   health_topic       43985 non-null  object
 4   indicator_metric   43985 non-null  object
 5   measurement_type   43985 non-null  object
 6   numeric_value      25875 non-null  float64
 7   demographic_group  43985 non-null  object
dtypes: float64(1), int64(1), object(6)
memory usage: 2.7+ MB

In [7]:
df[df.duplicated()]

Empty DataFrame
Columns: [year, state_code, state_name, health_topic, indicator_metric, measurement_type, numeric_value, demographic_group]
Index: []

In [8]:
df.rows = df.shape[0]
df.head()

,year,state_code,state_name,health_topic,indicator_metric,measurement_type,numeric_value,demographic_group
0,2019,AL,Alabama,Tobacco,Quit attempts in the past year among adult cur...,Crude Prevalence,NaN,"Hawaiian or Pacific Islander, non-Hispanic"
1,2019,CT,Connecticut,Cardiovascular Disease,High cholesterol among adults who have been sc...,Crude Prevalence,30.0,Hispanic
2,2019,DE,Delaware,Cardiovascular Disease,High blood pressure among adults,Crude Prevalence,38.8,"White, non-Hispanic"
3,2019,DE,Delaware,Cardiovascular Disease,Diseases of the heart mortality among all peop...,Number,2053.0,Overall
4,2019,DE,Delaware,Diabetes,Gestational diabetes among women with a recent...,Crude Prevalence,12.5,"White, non-Hispanic"

In [11]:
plt.hist()

plt.title('Age Distribution')
plt.xlabel('Age')
plt.ylabel('Frequency')

plt.show()

NameError: name 'plt' is not defined